// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

import "./Verifier.sol";

/// @title ZKGatedAccess
/// @notice Grants access to a gated API by verifying a ZK membership proof on-chain.
///         The agent proves it belongs to the set of registered agents (Merkle tree)
///         WITHOUT revealing its agent ID.
/// @dev Uses the Noir UltraHonk verifier generated by Barretenberg.
contract ZKGatedAccess {
    /// @notice The on-chain ZK proof verifier (Noir UltraHonk)
    HonkVerifier public immutable verifier;

    /// @notice The current Merkle root of allowed agent IDs
    bytes32 public merkleRoot;

    /// @notice Contract owner (can update the Merkle root)
    address public owner;

    /// @notice Emitted when a proof is successfully verified
    event AccessGranted(bytes32 indexed merkleRoot, bytes32 proofHash);

    /// @notice Emitted when access is denied (invalid proof)
    event AccessDenied(bytes32 indexed merkleRoot, bytes32 proofHash);

    /// @notice Emitted when the Merkle root is updated
    event MerkleRootUpdated(bytes32 oldRoot, bytes32 newRoot);

    error OnlyOwner();
    error InvalidRoot();

    modifier onlyOwner() {
        if (msg.sender != owner) revert OnlyOwner();
        _;
    }

    constructor(address _verifier, bytes32 _merkleRoot) {
        verifier = HonkVerifier(_verifier);
        merkleRoot = _merkleRoot;
        owner = msg.sender;
    }

    /// @notice Verify a ZK proof of agent membership
    /// @param _proof The serialized UltraHonk proof
    /// @param _publicInputs The public inputs array (first element = merkle root, rest = aggregation object)
    /// @return granted True if the proof is valid and the agent is in the allowed set
    function verifyAccess(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external returns (bool granted) {
        // The first public input must match the stored Merkle root
        if (_publicInputs.length == 0 || _publicInputs[0] != merkleRoot) {
            revert InvalidRoot();
        }

        // Verify the ZK proof on-chain
        try verifier.verify(_proof, _publicInputs) returns (bool result) {
            granted = result;
        } catch {
            granted = false;
        }

        if (granted) {
            emit AccessGranted(merkleRoot, keccak256(_proof));
        } else {
            emit AccessDenied(merkleRoot, keccak256(_proof));
        }
    }

    /// @notice Update the Merkle root (e.g., when agents are added/removed)
    /// @param _newRoot The new Merkle root
    function updateMerkleRoot(bytes32 _newRoot) external onlyOwner {
        bytes32 old = merkleRoot;
        merkleRoot = _newRoot;
        emit MerkleRootUpdated(old, _newRoot);
    }

    /// @notice Transfer ownership
    function transferOwnership(address _newOwner) external onlyOwner {
        owner = _newOwner;
    }
}
